name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Install Dependencies
        run: go mod tidy

      # 安装 golangci-lint
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2

      # 将 golangci-lint 的路径加入 PATH
      - name: Add golangci-lint to PATH
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      # 执行测试
      - name: Run Tests
        run: go test -v ./...

      # 执行 Lint 检查
      - name: Run Lint
        run: golangci-lint run
